name: Add To Copilot workshop
description: Request a new workshop to be added to Copilot.
title: "Add To Copilot workshop: "
labels: [enhancement]
body:
  - components:
    - type: input
      id: start_date
      attributes:
        label: Start date
        description: Please select the start date of the workshop.
        inputType: date
        required: true
    - type: input
      id: end_date
      attributes:
        label: End date
        description: Please select the end date of the workshop.
        inputType: date
        required: true
    - type: input
      id: workshop_name
      attributes:
        label: Workshop name
        description: Please enter the name of the workshop.
        required: true
    - type: input
      id: workshop_host
      attributes:
        label: Workshop host
        description: Please enter the name of the workshop host.
        required: true
    - type: dropdown
      id: location
      attributes:
        label: Location
        description: Please select the location of the workshop.
        options:
          - label: In person
            value: in_person
          - label: Virtual
            value: virtual
        required: true
