name: Join Workshop
description: Join workshop hosted by GitHub or Microsoft employees
title: "Join Workshop"
labels: [new-workshop]
body:
  - type: markdown
    id: start_date
    attributes:
      description: Please select the start date of the workshop.
      type: textarea
      required: true
  
