name: Join Workshop
description: Issue form for attendees to participate in workshop hosted by GitHub or Microsoft attendees
title: "Join Workshop"
labels: [new-workshop]
body:
  - type: markdown
    attributes:
      value: |
        This should be helpful!
  - type: input
    attributes:
      label: Name of workshop
      description: What is the name of your workshop
    validations:
      required: true
  - type: input
    attributes:
      label: Start date
      description: At what date will workshop attendees need access to this org? (Month Date, Year)
    validations:
      required: true
  - type: input
    attributes:
      label: End date
      description: At what date will workshop attendees no longer need access to this org? (Month Date, Year)
    validations:
      required: true
  - type: dropdown
    attributes:
      multiple: true
      label: Location
      description: Is this workshop virtual or in person?
      options:
        - "Virtual"
        - "In person"
        - "Hybrid"
    validations:
      required: true

