name: Create Workshop File

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  create_file:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'new-workshop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create file
        run: |
          name=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Name of workshop\n\n).*')
          start_date=$(echo "${{ github.event.issue.body }}" | grep -oP '(?<=### Start date\n\n).*')
          file_name=$(echo "${name}${start_date}" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]' | tr -d ',')
          touch "${file_name}.md"
