name: Create Workshop File

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  create_file:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'new-workshop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install grep
        run: sudo apt-get update && sudo apt-get install -y grep
      - name: Extract workshop name
        id: extract
        run: |
          body="${{ github.event.issue.body }}"
          name=$(echo "${body}" | sed -n 's/^### Name of workshop\s*//p')
          echo "name=${name}" >> $GITHUB_ENV
      - name: Create file
        id: create_file
        run: |
          name="${{ steps.extract.outputs.name }}"
          file_name=$(echo "${name}" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]' | tr -d ',')
          mkdir -p workshops
          touch "workshops/${file_name}.md"
          echo "file_name=${file_name}" >> $GITHUB_ENV

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Create workshops/${{ env.file_name }}.md"
