name: Create Workshop File

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  create_file:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'new-workshop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create file
        run: |
          touch test.md
