name: Create Workshop File

on:
  issues:
    types: [labeled]
  pull_request:
    types: [labeled]

jobs:
  create_file:
    runs-on: ubuntu-latest
    if: ${{ github.event.label.name == 'new-workshop' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Create file
        run: |
          mkdir -p workshops
          touch workshops/test.md
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "Create workshops/test.md"
